### ISSUE TITLE
No longer on the firefox addon store

### ISSUE THREAD

**Issue by TheW0LVERIN3** [JothCoder/smartschool-plus#1] opened 2021-09-11 07:49 UTC
The extension seems to have been taken off of https://addons.mozilla.org/

**Comment by jonatcln** [comment] 2021-09-12 20:24
Yes, I have indeed taken the add-on off. Since I no longer have easy direct access to Smartschool, it is not feasible for me to further maintain and develop this add-on. I also cannot guarantee that the add-on will continue to work as intended (due to Smartschool updates), which is why I decided to remove the add-on from AMO. I might also archive this repository soon, but you can still fork it if you're interested!

I will close this issue for now, but feel free to ask any further questions.

**Closed as completed by jonatcln** 2021-09-12 20:24 UTC
